name: storage_space_fork
description: Get the free, available and total storage space for the device. Utility helpers for readable sizes
version: 1.1.2
homepage: https://github.com/takeoutfm/storage_space
repository: https://github.com/takeoutfm/storage_space

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: flowmobile.storage_space
        pluginClass: StorageSpacePlugin
      ios:
        pluginClass: StorageSpacePlugin
